name: Auto Assign Issues

on:
  issues:
    types:
      - opened

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Issue
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          github-token: ${{ secrets.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 }}
          assignees: KateBrick # Replace 'username' with the GitHub username of the team member
